/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.1.2-13-gb45da36a29-20241114"
#endif /* AVUTIL_FFVERSION_H */
